#include "../../src/press.h"
#include "../../src/util.h"
#include "../../src/document.h"
#include "../../src/tokenise.h"
#include "../../src/validate.h"
#include "../../src/finalise.h"
#include "../../src/generate.h"

#include "kpress_main.c"

#include "../../src/roman_numeral.c"
#include "../../src/odt.c"
#include "../../src/html.c"
#include "../../src/epub.c"
#include "../../src/validate.c"
#include "../../src/finalise.c"
#include "../../src/util.c"
#include "../../src/zip.c"
#include "../../src/crc32.c"

#include "../../src/tokenise_internal.h"
#include "../../src/tokenise_metadata.c"
#include "../../src/tokenise.c"